// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentenceManagement.Api.Models;

namespace SentenceManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220411120335_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WordManagement.Models.Sentence", b =>
                {
                    b.Property<int>("SentenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SentenceId");

                    b.ToTable("Sentences");

                    b.HasData(
                        new
                        {
                            SentenceId = 1,
                            Content = "Hello World!"
                        },
                        new
                        {
                            SentenceId = 2,
                            Content = "Goodbye cruel World."
                        },
                        new
                        {
                            SentenceId = 3,
                            Content = "Whatever you say is only you're opinion."
                        },
                        new
                        {
                            SentenceId = 4,
                            Content = "When the blueberry sings and the mocking bird hums."
                        },
                        new
                        {
                            SentenceId = 5,
                            Content = "When comes and the sun chaseth the darkness away."
                        });
                });

            modelBuilder.Entity("WordManagement.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfWord")
                        .HasColumnType("int");

                    b.HasKey("WordId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            WordId = 1,
                            Descrip = "Box",
                            TypeOfWord = 0
                        },
                        new
                        {
                            WordId = 2,
                            Descrip = "Car",
                            TypeOfWord = 0
                        },
                        new
                        {
                            WordId = 3,
                            Descrip = "Case",
                            TypeOfWord = 0
                        },
                        new
                        {
                            WordId = 4,
                            Descrip = "Ride",
                            TypeOfWord = 1
                        },
                        new
                        {
                            WordId = 5,
                            Descrip = "Sit",
                            TypeOfWord = 1
                        },
                        new
                        {
                            WordId = 6,
                            Descrip = "Sing",
                            TypeOfWord = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
